USE [master]
GO

/****** Object:  Database [AdvancedTasksDW]    Script Date: 3/4/2020 8:47:59 PM ******/
CREATE DATABASE [AdvancedTasksDW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdvancedTasksDW', FILENAME = N'C:\SQLSERVER\MSSQL14.MSSQLSERVER\MSSQL\DATA\AdvancedTasksDW.mdf' , SIZE = 1122304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AdvancedTasksDW_log', FILENAME = N'C:\SQLSERVER\MSSQL14.MSSQLSERVER\MSSQL\DATA\AdvancedTasksDW_log.ldf' , SIZE = 6496256KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdvancedTasksDW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdvancedTasksDW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET ARITHABORT OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdvancedTasksDW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdvancedTasksDW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdvancedTasksDW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdvancedTasksDW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET RECOVERY FULL 
GO

ALTER DATABASE [AdvancedTasksDW] SET  MULTI_USER 
GO

ALTER DATABASE [AdvancedTasksDW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdvancedTasksDW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdvancedTasksDW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdvancedTasksDW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AdvancedTasksDW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AdvancedTasksDW] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AdvancedTasksDW] SET  READ_WRITE 
GO


