USE [master]
GO

/****** Object:  Database [AdvancedTasks]    Script Date: 3/4/2020 10:10:49 PM ******/
CREATE DATABASE [AdvancedTasks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Standard', FILENAME = N'C:\SQLSERVER\MSSQL14.MSSQLSERVER\MSSQL\DATA\Standard.mdf' , SIZE = 860160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Standard_log', FILENAME = N'C:\SQLSERVER\MSSQL14.MSSQLSERVER\MSSQL\DATA\Standard_log.ldf' , SIZE = 4530176KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdvancedTasks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdvancedTasks] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdvancedTasks] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AdvancedTasks] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AdvancedTasks] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AdvancedTasks] SET ARITHABORT OFF 
GO

ALTER DATABASE [AdvancedTasks] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdvancedTasks] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdvancedTasks] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdvancedTasks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdvancedTasks] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdvancedTasks] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AdvancedTasks] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdvancedTasks] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AdvancedTasks] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdvancedTasks] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdvancedTasks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdvancedTasks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdvancedTasks] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdvancedTasks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdvancedTasks] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdvancedTasks] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdvancedTasks] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdvancedTasks] SET RECOVERY FULL 
GO

ALTER DATABASE [AdvancedTasks] SET  MULTI_USER 
GO

ALTER DATABASE [AdvancedTasks] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdvancedTasks] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdvancedTasks] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdvancedTasks] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AdvancedTasks] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AdvancedTasks] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AdvancedTasks] SET  READ_WRITE 
GO


